Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story9.urls')),
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.registerPage, name="registerPage"),
    path('login/', views.loginPage, name="loginPage"),
    path('logout', views.logoutPage, name='logoutPage')
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='story9:loginPage')
def index(request):
    user = request.user
    context = {'user': user}
    return render(request, 'story9/index.html', context)

def registerPage(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            messages.success(request, "Your account created successfully, please login")
            return redirect('story9:loginPage')
    context = {'form':form}
    return render(request, 'story9/register.html', context)

def loginPage(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('story9:index')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'story9/login.html', context)

def logoutPage(request):
    logout(request)
    messages.success(request, "Logout successfully")
    return redirect('story9:loginPage')

story9/templates/story9/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block css %}
    
    {% endblock css %}
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>    
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    {% block js %}
    
    {% endblock js %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

story9/templates/story9/index.html
{% extends 'story9/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'story9/style.css' %}">
{% endblock css %}
{% block title %}Home{% endblock title %}
{% block content %}
<div class="wrapper d-flex flex-column justify-content-center align-items-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h3>Hello, {{ request.user }}</h3>
        <p class="m-0">Thank you for logging in to my page!</p>
    </div>
    <a href="{% url 'story9:logoutPage' %}">
        <button type="button" class="btn btn-light btn-logout">Logout</button>
    </a>
</div>
{% endblock content %}

story9/templates/story9/login.html
{% extends 'story9/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'story9/register.css' %}">
{% endblock css %}
{% block title %}Login{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">You've logged in</h4>
        <a href="{% url 'story9:index' %}">
            <button type="submit" class="btn btn-light btn-auth align-self-center">Back to Home</button>
        </a>
    </div>
</div>
{% else %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">Welcome Back!</h4>
        <form action="" method="post" class="d-flex flex-column justify-content-center">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" autocomplete="username">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" name="password" autocomplete="current-password">
            </div>
            {% for message in messages %}
                {% if message.tags == 'info' %}
                    <small class="form-text text-danger form-error mt-0 mb-3">{{ message }}</small> 
                {% endif %}
                {% if message.tags == 'success' %}
                    <small class="form-text text-success form-error mt-0 mb-3">{{ message }}</small> 
                {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-light btn-auth align-self-center">Login</button>
            <p>Don't have an account? <a href="{% url 'story9:registerPage' %}">Sign Up</a></p>
        </form>
    </div>
</div>
{% endif %}
{% endblock content %}
{% block js %}
<script>
    $("input").addClass("form-control")
    $("input").eq(1).attr("placeholder", 'Username...')
    $("input").eq(2).attr("placeholder", 'Enter Password...')
</script>
{% endblock js %}

story9/templates/story9/register.html
{% extends 'story9/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'story9/register.css' %}">
{% endblock css %}
{% block title %}Register{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
  <div class="box d-flex flex-column justify-content-center align-items-center">
      <h4 class="title">You've logged in</h4>
      <a href="{% url 'story9:index' %}">
          <button type="submit" class="btn btn-light btn-auth align-self-center">Back to Home</button>
      </a>
  </div>
</div>
{% else %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">Register</h4>
        <form action="" method="post" class="d-flex flex-column justify-content-center">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                {{form.username}}
                <small class="form-text text-danger form-error">{{ form.errors.username }}</small> 
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                {{form.password1}}
                <small class="form-text text-danger form-error">{{ form.errors.password1 }}</small> 
              </div>
              <div class="form-group">
                <label for="exampleInputPassword2">Confirm Your Password</label>
                {{form.password2}}
                <small class="form-text text-danger form-error">{{ form.errors.password2 }}</small> 
              </div>
              <button type="submit" class="btn btn-light btn-auth align-self-center">Register</button>
            <p>Already have an account? <a href="{% url 'story9:loginPage' %}">Sign In</a></p>
        </form>
    </div>
</div>
{% endif %}
{% endblock content %}
{% block js %}
<script>
    $("input").addClass("form-control");
    $("input").eq(1).attr("placeholder", 'Username...');
    $("input").eq(2).attr("placeholder", 'Enter Password...');
    $("input").eq(3).attr("placeholder", 'Re-Enter Password...');
</script>
{% endblock js %}